openapi: '3.0.2'
info:
  title: todos
  version: '1.0'
servers:
  - url: http://localhost:3000/api
  # - url: https://api.server.test/v1

paths:         
  /todos:
    get:
      description: get all todos of the signed in user
      security:
        - jwt: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Todo'
        '401':
          $ref: '#/components/responses/AuthRequired'
    
    post:
      description: create a new todo
      security:
        - jwt: []
      requestBody:
        $ref: '#/components/requestBodies/TodoBody'
      responses:
        '200':
          $ref: '#/components/responses/TodoResponse'
        '400':
          $ref: '#/components/responses/BadTodo'
        '401':
          $ref: '#/components/responses/AuthRequired'
          

  /todos/{id}:
    put:
      description: update a todo
      security:
        - jwt: []
      parameters:
        - in: path
          name: id
          schema:
            type : string
          required: true
      requestBody:
        $ref: '#/components/requestBodies/TodoBody'
      responses:
        '200':
          $ref: '#/components/responses/TodoResponse'
        '400':
          $ref: '#/components/responses/BadTodo'
        '401':
          $ref: '#/components/responses/AuthRequired'
        '404':
          $ref: '#/components/responses/TodoNotFound'

    delete:
      description: delete a todo
      security:
        - jwt: []
      parameters:
        - in: path
          name: id
          schema:
            type : string
          required: true
      responses:
        '200':
          $ref: '#/components/responses/TodoResponse'
        '401':
          $ref: '#/components/responses/AuthRequired'
        '404':
          $ref: '#/components/responses/TodoNotFound' 

  /auth/signin:
    post:
      description: sign in
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: saul.goodman@jmm.com
                password:
                  type: string
                  example: Ice Station Zebra
      responses:
        '200':
          $ref: '#/components/responses/JWTResponse'
        '400':
          description: Bad request (credentials are not valid or malformed)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      message:
                        type: string
                        example: request body should contain {email<string>, password:<string>}
        '404':
          description: Not Found (user does not exist) 
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      message:
                        type: string
                        example: email is not registered, want to sign up?
          

  /auth/signup:
    post:
      description: sign up a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  $ref: '#/components/schemas/User'
      responses:
        '200':
          $ref: '#/components/responses/JWTResponse'
        '400':
          description: Bad request (credentials are malformed or user already exists)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      message:
                        type: string
                        example: request body should contain {user:{name:<string>, email:<string>, password:<string>}}

components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer

  schemas:
    Todo: 
      type: object
      properties:
        id:
          type: string
          readOnly: true
        name:
          type: string
          example: film a commercial
    
    User:
      type: object
      properties:
        id:
          type: string
          readOnly: true
        email:
          type: string
          example: saul.goodman@jmm.com
        name:
          type: string
          example: Saul Goodman
        password:
          type: string
          example: Ice Station Zebra

  requestBodies:
    TodoBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              todo:
                $ref: '#/components/schemas/Todo'
  responses:
    TodoResponse:
      description: a todo
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: '#/components/schemas/Todo'
    
    JWTResponse:
      description: JWT
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: string

    AuthRequired:
      description: not authenticated, authorization is required
      headers:
        'WWW-Authenticate':
          schema:
            type: string
            description: authorization header is required
            example: Bearer realm="accessing todos"
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  message:
                    type: string
                    example: sign in is required

    BadTodo:
      description: todo object is malformed
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  message:
                    type: string
                    example: request body should contain {todo:{name:<string>}}

    TodoNotFound:
      description: no such todo for the specified id
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  message:
                    type: string
                    example: no such todo with id:e3f7de63-e740-4c84-99ff-e9d043f0ffe0