version: "3.7"

services:
  app:
    image: node:14-alpine
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
      - 3433:3433
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: todos
  
  mysql:
    image: mysql:8.0
    volumes:
      - mysql-clones-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todos


volumes:
  mysql-clones-db: